# Generated by Django 4.2.4 on 2023-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploaded_images/")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "Normal"), ("abnormal", "Abnormal")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
