# Generated by Django 4.2.4 on 2023-09-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_input", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="label",
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
