# Generated by Django 4.2.4 on 2023-09-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_input", "0002_remove_uploadedimage_label_uploadedimage_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
