# Generated by Django 4.2.4 on 2023-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_input", "0003_uploadedimage_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="image_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
